### ISSUE TITLE
Undefined `time` function used in `importer.py`

### ISSUE THREAD

**Issue by MystPi** [Darth-Ness/Katana-HTML-Renderer#12]
I'm not sure what the `time` function is here, but it's not defined.
https://github.com/Darth-Ness/Katana-HTML-Renderer/blob/ac3f71bd692d22d249af5c03599cdf11e3ae5650/src/importer.py#L19
Anyone who tries to use Katana will get an error; I suggest you fix it.

**Comment by Darth-Ness** [comment]
Hmm, time is a module I use to profile code sometimes. I guess I forgot to remove it.

**Comment by MystPi** [comment]
> Hmm, time is a module I use to profile code sometimes. I guess I forgot to remove it. This bug only exists in the main branch. Which by this point is extremely out of date. However, if you need to use the main branch for some reason, you can fix it by removing that line, or importing the time module.

Can't you just fix it?

**Comment by Darth-Ness** [comment]
> > Hmm, time is a module I use to profile code sometimes. I guess I forgot to remove it. This bug only exists in the main branch. Which by this point is extremely out of date. However, if you need to use the main branch for some reason, you can fix it by removing that line, or importing the time module.
> 
> Can't you just fix it?

I'll be merging from dev soon. The issue will be fixed then.

**Comment by MystPi** [comment]
> > > Hmm, time is a module I use to profile code sometimes. I guess I forgot to remove it. This bug only exists in the main branch. Which by this point is extremely out of date. However, if you need to use the main branch for some reason, you can fix it by removing that line, or importing the time module.
> > 
> > 
> > Can't you just fix it?
> 
> I'll be merging from dev soon. The issue will be fixed then.

Okay, thanks!
