### ISSUE TITLE
Possibly major performance issue in renderMain.py.

### ISSUE THREAD

**Issue by Darth-Ness** [Darth-Ness/Katana-HTML-Renderer#15]
In the file renderMain.py there is the following while loop.
```Python
while(u < len(toRender)):
        if toRender[u] in textTags:
            renderText(toRender, u, root, isCentered)
        if "<img" in toRender[u]:
            import renderImage
            renderImage.startImage(root, toRender[u], isOnline, fileName, isCentered, tkinter)
        if "<button" in toRender[u] and not "/" in toRender[u]:
            tkinter.Button(root, text=toRender[u+1]).pack(side=tkinter.TOP, anchor=isCentered)
        if "<br" in toRender[u]:
            tkinter.Label(root, bg=root.cget('bg')).pack(side=tkinter.TOP, anchor=isCentered)
        if "<center" in toRender[u]:
            isCentered = "center"
        if "</center" in toRender[u]:
            isCentered = "nw"
        if "<title" in toRender[u]:
            root.title(toRender[u+1])
            u+=1
        if "<hr" in toRender[u]:
            renderHRule(root)
        if "<style>" in toRender[u]:
            import handleCSS
            handleCSS.doCSS(root, toRender, u)
            u = toRender.index("</style>")+1

```

Basically, this is the loop that runs through the parsed HTML and runs functions that render the HTML.
I found last night however, that if ```<h1>``` is spotted on the line, the line is still checked for ```<button>```, ```<img>``` etc.
I'm already looking into a fix, and hopefully will be able to release a patch soon.

May also be unrelated ,but I've heard that for loops or more performant than while loops. So it may be worth converting the above while loop into a for loop for further increased performance.

**Comment by Darth-Ness** [comment]
I was able to optimize this while loop into this
```Python
while(u < length):
        if toRender[u] in textTags or toRender[u] in tags:
            if toRender[u] in textTags:renderText(toRender, u, root, isCentered)
            elif "<img" in toRender[u]:
                import renderImage
                renderImage.startImage(root, toRender[u], isOnline, fileName, isCentered)
            elif "<button" in toRender[u]:Button(root, text=toRender[u+1]).pack(side=TOP, anchor=isCentered)
            elif "<br" in toRender[u]:Label(root, bg=root.cget('bg')).pack(side=TOP, anchor=isCentered)
            elif "<center" in toRender[u]:isCentered = "center"
            elif "</center" in toRender[u]:isCentered = "nw"
            elif "<title" in toRender[u]:root.title(toRender[u+1])
            elif "<hr>" in toRender[u]:renderHRule(root)
            elif "<style>" in toRender[u]:
                import handleCSS
                handleCSS.doCSS(root, toRender, u)
                u = toRender.index("</style>")+1
```
However, I dind't really see any performance increase.

**Comment by ninjamar** [comment]
I think you can put `break` at the end of the if statement. This break out of the loop (`while`).

**Comment by Darth-Ness** [comment]
> I think you can put `break` at the end of the if statement. This break out of the loop (`while`).

I actually tried that, but then the rest of the HTML code isn't rendered.

**Comment by ninjamar** [comment]
> > I think you can put `break` at the end of the if statement. This break out of the loop (`while`).
> 
> I actually tried that, but then the rest of the HTML code isn't rendered.

Try `continue` which continues to the next iteration. Also the imports should be at the top of the file since the module gets imported everytime the loop runs.

**Comment by Darth-Ness** [comment]
> > > I think you can put `break` at the end of the if statement. This break out of the loop (`while`).
> > 
> > 
> > I actually tried that, but then the rest of the HTML code isn't rendered.
> 
> Try `continue` which continues to the next iteration. Also the imports should be at the top of the file since the module gets imported everytime the loop runs.

Where should the `continue` command be?  I actually had that in a earlier version of Katana, but the problem with that is even if there is no images on a page, the dependencies for them or still imported. I will look into a solution for the problem.

**Comment by ninjamar** [comment]
> Where should the `continue` command be? I actually had that in a earlier version of Katana, but the problem with that is even if there is no images on a page, the dependencies for them or still imported. I will look into a solution for the problem.

The `continue` should be at the end of every if, before the next one gets evaluated. It is fine if the modules get imported even if they aren't always needed in this scenario. The modules aren't thousands of lines so it shouldn't make too much lag.

**Comment by Darth-Ness** [comment]
> > Where should the `continue` command be? I actually had that in a earlier version of Katana, but the problem with that is even if there is no images on a page, the dependencies for them or still imported. I will look into a solution for the problem.
> 
> The `continue` should be at the end of every if, before the next one gets evaluated. It is fine if the modules get imported even if they aren't always needed in this scenario. The modules aren't thousands of lines so it shouldn't make too much lag.

So put `continue` and `break` or just `continue`? I think I have a different solution which I'll check at in a little while.

**Comment by ninjamar** [comment]
> > > Where should the `continue` command be? I actually had that in a earlier version of Katana, but the problem with that is even if there is no images on a page, the dependencies for them or still imported. I will look into a solution for the problem.
> > 
> > 
> > The `continue` should be at the end of every if, before the next one gets evaluated. It is fine if the modules get imported even if they aren't always needed in this scenario. The modules aren't thousands of lines so it shouldn't make too much lag.
> 
> So put `continue` and `break` or just `continue`? I think I have a different solution which I'll check at in a little while.

Just `continue`

**Comment by Darth-Ness** [comment]
I tried to put a `continue` statement in. However, the entire script just stops there. Is there a fix for this?

**Comment by ninjamar** [comment]
> I tried to put a `continue` statement in. However, the entire script just stops there. Is there a fix for this?

Another idea. What python version are you using? If you have 3.10, I think you can use a match-case thing. https://towardsdatascience.com/the-match-case-in-python-3-10-is-not-that-simple-f65b350bb025

**Comment by Darth-Ness** [comment]
> > I tried to put a `continue` statement in. However, the entire script just stops there. Is there a fix for this?
> 
> Another idea. What python version are you using? If you have 3.10, I think you can use a match-case thing. https://towardsdatascience.com/the-match-case-in-python-3-10-is-not-that-simple-f65b350bb025

Hmm, thanks. A the moment I believe I'm using 3.9 but I'll check if a update is available.

**Comment by ninjamar** [comment]
Ok

**Comment by Darth-Ness** [comment]
There doesn't appear to be such a performance issue in renderMain.py

**Comment by ninjamar** [comment]
> There doesn't appear to be such a performance issue in renderMain.py

ok?
