### ISSUE TITLE
JSON based-tags.

### ISSUE THREAD

**Issue by qbjl** [Darth-Ness/Katana-HTML-Renderer#17]
Add a tags.json file that basically has all of the tags in one JSON file, and then in those have the name and what the tags do.

example:

```json
"tags": [
  {
    "tag": "h1",
    "singular": false, // like <input type="text" />
    "css": {
      "text-size": 25
    }
  },
  // ...
]
```

**Comment by Darth-Ness** [comment]
What would be the point of this?

**Comment by qbjl** [comment]
> What would be the point of this?

Easier additions for tags.

**Comment by Darth-Ness** [comment]
> > What would be the point of this?
> 
> Easier additions for tags.

How would this make adding new tags easier?

**Comment by vercte** [comment]
@Darth-Ness I would assume you could define some default CSS values, for example:
`"tags": [
  {
    "tag": "button",
    "empty": false,
    "agent-css": {
      "font-family": "sans-serif",
      "background-color": "lightgrey",
      "border-radius": "3px",
      "border": "1px black solid"
    }
  },
  // ...
]`

**Comment by Darth-Ness** [comment]
> @Darth-Ness I would assume you could define some default CSS values, for example: `"tags": [ { "tag": "button", "empty": false, "agent-css": { "font-family": "sans-serif", "background-color": "lightgrey", "border-radius": "3px", "border": "1px black solid" } }, // ... ]`

Yes, but how would that make adding new tags any easier?

**Comment by hello-smile6** [comment]
> > @Darth-Ness I would assume you could define some default CSS values, for example: `"tags": [ { "tag": "button", "empty": false, "agent-css": { "font-family": "sans-serif", "background-color": "lightgrey", "border-radius": "3px", "border": "1px black solid" } }, // ... ]`
> 
> Yes, but how would that make adding new tags any easier?

Not sure
