### ISSUE TITLE
Add tags for the repository

### ISSUE THREAD

**Issue by ninjamar** [Darth-Ness/Katana-HTML-Renderer#7]
Please tag this repository

**Comment by Darth-Ness** [comment]
Sorry, but I'm kinda unfamiliar with GitHub at the moment. Is that what you wanted?

**Comment by DelightedDuck** [comment]
you should probably at a tag called "html renderer" too

**Comment by Darth-Ness** [comment]
I added that one as well.

**Comment by ninjamar** [comment]
yep
